FROM management-api-for-apache-cassandra-builder as builder

FROM cassandra:3.11

COPY --from=builder /build/management-api-common/target/datastax-mgmtapi-common-0.1.0-SNAPSHOT.jar /etc/cassandra/
COPY --from=builder /build/management-api-agent/target/datastax-mgmtapi-agent-0.1.0-SNAPSHOT.jar /etc/cassandra/
COPY --from=builder /build/management-api-server/target/datastax-mgmtapi-server-0.1.0-SNAPSHOT.jar /opt/mgmtapi/
COPY --from=builder /build/management-api-shim-3.x/target/datastax-mgmtapi-shim-3.x-0.1.0-SNAPSHOT.jar /opt/mgmtapi/
COPY --from=builder /build/management-api-shim-4.x/target/datastax-mgmtapi-shim-4.x-0.1.0-SNAPSHOT.jar /opt/mgmtapi/

ENV TINI_VERSION v0.18.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

RUN set -eux; \
  rm -fr /etc/apt/sources.list.d/*; \
  rm -rf /var/lib/apt/lists/*; \
  apt-get update; \
  apt-get install -y --no-install-recommends wget iproute2; \
  rm -rf /var/lib/apt/lists/*

ENV MCAC_VERSION 0.1.7
ADD https://github.com/datastax/metric-collector-for-apache-cassandra/releases/download/v${MCAC_VERSION}/datastax-mcac-agent-${MCAC_VERSION}.tar.gz /opt/mcac-agent_amd64.tar.gz
ADD https://github.com/johntrimble/metric-collector-for-apache-cassandra/releases/download/v0.1.12/datastax-mcac-agent-0.1.12_arm64.tar.gz /opt/mcac-agent_arm64.tar.gz

ARG TARGETARCH
RUN if [ "$TARGETARCH" = "arm64" ]; then \
    mkdir /opt/mcac-agent && tar zxvf /opt/mcac-agent_arm64.tar.gz -C /opt/mcac-agent --strip-components 1 && rm /opt/mcac-agent_arm64.tar.gz; \
  else \
    mkdir /opt/mcac-agent && tar zxvf /opt/mcac-agent_amd64.tar.gz -C /opt/mcac-agent --strip-components 1 && rm /opt/mcac-agent_amd64.tar.gz; \
  fi

# backwards compat with upstream ENTRYPOINT
COPY scripts/docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh && \
  ln -sf /usr/local/bin/docker-entrypoint.sh /docker-entrypoint.sh

EXPOSE 9103
EXPOSE 8080

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["mgmtapi"]
