name: Docker Build

on:
  push:
    branches: cassandra-mgmtapi-multiarch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Management API in docker
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <?xml version="1.0" encoding="UTF-8"?>
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
            <interactiveMode>false</interactiveMode>
          </settings>
          EOF
          cp ~/.m2/settings.xml settings.xml
          docker build -t management-api-for-apache-cassandra-builder -f ./Dockerfile-build ./
      - name: Setup Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          version: latest
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build image
        run: |
          docker buildx build --push \
            --tag johntrimble/cassandra-mgmtapi-multiarch:3.11.6 \
            --file Dockerfile-3_11 \
            --platform linux/amd64,linux/arm64 .
